### PR TITLE
Update to 0.2.0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by unseen-ninja** [comment]
Awesome! Thanks a lot for updating the port. Two teeny-tiny things:

1) I'd suggest renaming the Frappé file to just `frappe` because the `é` *could potentially* cause issues on some systems.

2) It would be awesome to have a preview pictures showing off all four flavours. This is optional for the PR to get merged tho. Some examples would be [Kitty](https://github.com/catppuccin/kitty), [YouTube](https://github.com/catppuccin/youtube) [Dark Reader](https://github.com/catppuccin/dark-reader).

**Comment by ghost** [comment]
Alright cool! I'll be on it!

**Review by ghost — COMMENTED** [review]
Done, the wallpaper link in the readme should link to https://raw.githubusercontent.com/catppuccin/konsole/main/assets/konsole.png which will be the image I just added.

**Comment by unseen-ninja** [comment]
Looking good, thanks again. ^—^

**Pull request merged**
